class Round < ApplicationRecord
  belongs_to :game
  has_many :answers, dependent: :destroy

  enum :status, { answering: 0, reviewing: 1, voting: 2, completed: 3 }

  # Use round_number in URLs instead of id
  def to_param
    round_number.to_s
  end

  QUESTIONS = [
    "What's your favorite color and why does it matter?",
    "Why are dogs better than cats (or are they)?",
    "Pineapple on pizza - defend your position.",
    "Why are you a morning person or night owl?",
    "What's your weirdest habit that would make people judge you?",
    "Coffee or tea and why is the other one terrible?",
    "What's your guilty pleasure song that you're embarrassed about?",
    "Beach or mountains and why is the other boring?",
    "What's your phone wallpaper right now and why?",
    "Sweet or savory - why are you choosing wrong?",
    "What's the last embarrassing thing you googled?",
    "Socks with sandals: defend it or roast it.",
    "What's your worst cooking disaster story?",
    "What's a popular opinion that you actually disagree with?",
    "What emoji do you overuse and why?",
    "What's the most useless talent you're weirdly proud of?",
    "Selfie stick: genius invention or total embarrassment?",
    "If your life had a soundtrack, what's the most cringe song on it?",
    "Describe your most awkward small talk experience in excruciating detail.",
    "What's the strangest thing you've panic-bought online at 2 AM?",
    "Roommate horror stories: what's your most unhinged tale?",
    "Instant ramen hack that you're convinced is culinary genius?",
    "What YouTube rabbit hole are you ashamed of falling into?",
    "Worst dating app conversation that still makes you cringe?",
    "If your browser history was suddenly projected in public, what would you die of embarrassment about?",
    "What childhood fashion choice haunts you to this day?",
    "Describe the most ridiculous excuse you've ever used to get out of something.",
    "What's your most irrational fear that makes zero sense?",
    "Unpopular tech opinion that would start a Twitter war?",
    "Describe a conspiracy theory you lowkey believe in.",
    "What's the most unnecessary purchase you've ever justified to yourself?",
    "Karaoke song you'd absolutely nail but would never admit publicly?",
    "Your most catastrophic attempt at being 'cool'?",
    "What household chore do you irrationally despise?",
    "Describe a random skill you have that serves zero practical purpose.",
    "What's the weirdest thing you do when absolutely nobody is watching?",
    "Your most embarrassing autocorrect disaster?",
    "Defend your most problematic food combination.",
    "What trend did you participate in that you now completely regret?",
    "Describe the most passive-aggressive text you've ever sent.",
    "What's your go-to procrastination method that's borderline performance art?",
    "Worst advice you've ever received that you secretly followed?",
    "If your pet could talk, what horrifying secrets would they expose about you?",
    "What social media challenge would you absolutely refuse to do?",
    "Describe a personal 'Florida Man' moment in your life.",
    "Your most ridiculous impulse purchase triggered by an Instagram ad?",
    "What's the most unnecessarily complicated way you do a simple task?",
    "Describe a hill you're willing to die on that makes no sense.",
    "Worst DIY project that went completely off the rails?",
    "If your life was a reality show, what would be its most cringe segment?",
    "Describe the most unnecessarily dramatic way you've quit something.",
    "What's the strangest thing that lives in your Notes app?",
    "Your most questionable midnight snack creation?",
    "Describe a skill you learned purely out of pure spite.",
    "What's the most embarrassing thing in your search history right now?",
    "Your most chaotic personal routine that somehow works?",
    "Describe a situation where you were dramatically overconfident.",
    "What's the most bizarre compliment you've ever received?",
    "Your most unhinged productivity hack?",
    "Describe a time you accidentally became the main character.",
    "What's a random opinion you hold that would start an argument?",
    "Your most ridiculous attempt at flirting?",
    "Describe a situation where you were way too honest.",
    "What's the most useless fact you know and love?",
    "Your most chaotic method of decision making?",
    "Describe a time you completely misread a social situation.",
    "What's the strangest thing you do to psych yourself up?",
    "Your most questionable fashion era?",
    "Describe a time you took a joke way too far.",
    "Your most chaotic morning routine?",
    "Describe a time you accidentally became an internet meme.",
    "What's the most ridiculous reason you've ever been late?",
    "Your most unhinged productivity playlist?",
    "Describe a situation where you were accidentally the coolest person in the room.",
    "What's the most bizarre way you've tried to impress someone?",
    "Your most questionable comfort TV show?",
    "Describe a time you completely misunderstood a cultural reference.",
    "What's the most unnecessary drama you've ever been involved in?",
    "Your most chaotic method of stress relief?",
    "Describe a time you took a compliment way too seriously.",
    "Your most unhinged shopping habit?",
    "Describe a situation where you were way too competitive.",
    "Your most chaotic method of conflict resolution?",
    "Describe a time you were accidentally profound.",
    "What's the most bizarre thing you find genuinely entertaining?",
    "Your most questionable hobby?",
    "Describe a time you completely missed the point.",
    "Your most chaotic approach to learning something new?",
    "What's the most ridiculous lie you successfully told as a kid?",
    "Which household chore do you secretly enjoy but would never admit publicly?",
    "What's the strangest thing you believed as a child that you're now embarrassed about?",
    "If you could instantly become an expert at one completely impractical skill, what would it be?",
    "Describe a time you accidentally dressed inappropriately for an event?",
    "What childhood memory makes you irrationally angry when you think about it?",
    "If your brain had browser history, what would be your most embarrassing search?",
    "What's the most ridiculous thing you've done to avoid confrontation?",
    "What's your secret lazy person superpower?",
    "If you could eliminate one mildly inconvenient thing from existence, what would it be?",
    "What's the most absurd punishment you received as a kid?",
    "Describe a time you misunderstood something completely and rolled with it?",
    "Describe a time you pretended to know something you absolutely didn't?",
    "What's your signature move when you're trying to look cool but failing?",
    "If you could send a message to your younger self, what would be your most sarcastic warning?",
    "Describe a time you were caught in a white lie that spiraled out of control?",
    "If you could instantly forget one awkward memory, what would it be?",
    "What's your weirdest comfort food combination?",
    "If you had to live with one commercial jingle in your head forever, which would drive you least crazy?",
    "What's the most bizarre thing you've done to avoid doing work?",
    "Describe a time you accidentally insulted someone while trying to be nice?",
    "What's your most irrational grudge against an inanimate object?",
    "If your life came with warning labels, what would they say?",
    "Describe a time you royally messed up a simple task?",
    "What's your signature move for getting out of uncomfortable situations?",
    "Describe a time you completely misunderstood modern slang?",
    "What's your go-to fake excuse when you don't want to do something?",
    "If your personality was a meme, which one would accurately describe you?",
    "What's the most embarrassing thing your family does that you can't stand?",
    "Describe a time you tried to look mature but came across as totally childish?",
    "What's your most irrational attachment to a random object?",
    "If you could eliminate one social obligation, what would it be?",
    "Describe a time you accidentally revealed too much information?",
    "If your brain had a blooper reel, what would be the headline moment?",
    "What's the most embarrassing childhood nickname?",
    "If you could rename yourself, what's the most chaotic name you'd choose?",
    "Describe a time you completely misjudged a situation?",
    "What's your signature move for avoiding direct questions?",
    "What's the most absurd thing you believed about adulthood as a kid?",
    "Describe a time you accidentally started a rumor?",
    "If you could instantly become an expert at one useless trivia topic, what would it be?",
    "What's the most embarrassing thing in your camera roll right now?",
    "Your most ridiculous method for procrastinating?",
    "If your personality was a condiment, what would it be and why?",
    "What's the most bizarre thing you've done to avoid small talk?",
    "Describe a time you completely misunderstood a joke?",
    "What's your secret talent that would surprise everyone?",
    "If you could broadcast one embarrassing moment to everyone you know, which would make you laugh the hardest?",
    "Describe a time you accidentally used the wrong tone in a message?",
    "What's your most irrational pet peeve about technology?",
    "Which internet challenge would you absolutely refuse to participate in?",
    "If your life had a loading screen, what would be the most embarrassing tip text?",
    "Autocorrect just changed your most important email - how do you explain the chaos?",
    "Defend your most irrational fear as completely rational.",
    "If your browser history could talk, what would it apologize for?",
    "Which tech startup idea is so bad it might actually work?",
    "What's the most chaotic good thing you've done this week?",
    "Explain your favorite meme as if it were a serious academic concept.",
    "If you could weaponize one of your personality flaws, what would it be?",
    "Which obsolete technology do you secretly miss?",
    "Describe your personality using only '90s movie quotes.",
    "If your sense of humor had a warning label, what would it say?",
    "Which social media trend makes you irrationally angry?",
    "If AI wrote your dating profile, what horrifying things would it include?",
    "Which Gen Z slang term should immediately be retired?",
    "If your pet could write a brutally honest Yelp review of you, what would it say?",
    "Describe your last awkward social interaction in excruciating detail.",
    "Which household chore would you outsource to a robot immediately?",
    "What's the most embarrassing playlist in your music library?",
    "If your imposter syndrome had a name, what would it be?",
    "Which startup buzzword makes you want to scream?",
    "Describe your communication style using only sandwich metaphors.",
    "What's the most chaotic thing in your Google search history?",
    "If you could turn one minor inconvenience into a supervillain, what would it be?",
    "Which outdated piece of technology are you most attached to?",
    "Explain your worst personality trait like it's a feature, not a bug.",
    "What's the most unnecessarily complicated routine in your life?",
    "If your inner monologue had a warning label, what would it say?",
    "Which internet argument have you been irrationally invested in?",
    "Describe your last existential crisis in the most dramatic way possible.",
    "If your procrastination could talk, what excuses would it make?",
    "Which millennial or Gen Z trait do you absolutely embody?",
    "Describe your friendship style using only food analogies.",
    "If your anxiety had a theme song, what would it be?",
    "Which social media trend do you secretly love but won't admit?",
    "Describe your work ethic using only game show metaphors.",
    "Which tech problem have you solved in the most MacGyver way possible?",
    "What's the most ridiculous thing you've done to avoid human interaction?",
    "If your imposter syndrome wrote a dating profile, what would it say?",
    "Which internet challenge would you absolutely destroy?",
    "Describe your communication style as a poorly translated instruction manual.",
    "If your browser history could testify in court, what would it reveal?",
    "Which startup idea is so bad it might actually revolutionize something?",
    "What's the most passive-aggressive email you've ever drafted?",
    "Describe your last awkward moment using only wrestling announcer language.",
    "If your sense of humor had a warning label, what bizarre cautions would it include?",
    "Which social media trend makes you irrationally passionate?",
    "If AI reviewed your life choices, what would its performance review say?",
    "Which Gen Z slang term are you secretly trying to make happen?",
    "Describe your last existential crisis as a noir detective monologue.",
    "What's the most ridiculous conspiracy theory you almost convinced someone of?",
    "If your procrastination wrote a self-help book, what would its title be?",
    "Which technological inconvenience would you eliminate first?",
    "Describe your personality using only '80s movie training montage logic.",
    "What's the most chaotic energy you've unleashed this month?",
    "If your inner voice had a dramatic backstory, what would it be?",
    "Which internet argument have you been low-key researching for weeks?",
    "What's the most unnecessary app you can't stop using?",
    "Describe your friendship dynamics using only wrestling team metaphors.",
    "If your anxiety could write a stand-up comedy routine, what would it joke about?",
    "Which social media trend do you predict will age terribly?",
    "What's the most absurd method you've used to motivate yourself?",
    "If your life had end-of-level video game stats, what would they reveal?",
    "Describe your worst personality trait as a dramatic movie trailer.",
    "What's the most spectacular social fail that still makes you cringe?",
    "What's the most awkward compliment you've ever received?",
    "If you could instantly become good at one thing, what hilariously impractical skill would you choose?",
    "What's the most irrational fear of a completely harmless thing?",
    "Which household chore do you secretly enjoy but would never admit?",
    "Describe a time you tried to be cool and epically failed?",
    "What's the most useless piece of advice you've ever received?",
    "If your life had a soundtrack, what embarrassing song would play during dramatic moments?",
    "What's your most useless superpower?",
    "If your life was a bad reality show, what would be its most cringe moment?"
  ]

  def self.generate_question(game)
    # Get all previously used questions in this game
    used_questions = game.rounds.pluck(:question)

    # Get available questions that haven't been used yet
    available_questions = QUESTIONS - used_questions

    # If we've used all questions, start over (shouldn't happen with 212 questions and 5 rounds)
    available_questions = QUESTIONS if available_questions.empty?

    available_questions.sample
  end

  def all_players_answered?
    expected_count = game.active_players.count
    actual_count = answers.count
    expected_count > 0 && actual_count >= expected_count
  end
end
